name: macOS Build
on:
  push:         # Keep empty to run on each branch when push the code. Otherwise use branches: [ master ]
    branches:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: Checkout Areg SDK source codes
        uses: actions/checkout@v6

      - name: Setup Java JDK to run code generator
        uses: actions/setup-java@v5.1.0
        with: 
          java-version: 17
          java-package: jre
          distribution: temurin

      - name: Ensure Xcode CLI Tools
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Set SDKROOT
        run: echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV

      - name: create build directory
        working-directory: ${{github.workspace}}
        run: mkdir build

      - name: Check SDK and architecture
        run: |
            clang -v
            echo $SDKROOT
            uname -m

      - name: Configure CMake for macOS native
        working-directory: ${{github.workspace}}
        run: cmake -S . -B build \
                    -DCMAKE_C_COMPILER=clang \
                    -DCMAKE_CXX_COMPILER=clang++ \
                    -DCMAKE_OSX_ARCHITECTURES=arm64 \
                    -DCMAKE_OSX_SYSROOT=$(xcrun --show-sdk-path) \
                    -DCMAKE_SYSTEM_NAME=Darwin  \
                    -DCMAKE_BUILD_TYPE=Release  \
                    -DAREG_COMPILER_FAMILY=llvm \
                    -DAREG_PROCESSOR=arm64

      - name: Build with CMake
        working-directory: ${{github.workspace}}
        run: cmake --build build --config ${{env.BUILD_TYPE}}      
